remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Tim M. Workshop SVK 2024"
description: "Join us for a 12-step workshop in slovakian mountains"
